# These are supported funding model platforms

github: [stevepederzani]
patreon: pederzani
custom: ['https://farcaster.xyz/ozmium.eth','https://www.clanker.world/clanker/0x148313DCDb7A7111EBEFA4871F6A7fef34833B07']
